name: smari-azure-iot-edge-test
version: '1.0.7'
summary: Extend cloud intelligence and analytics to edge devices 
description: 
  Testing Azure IoT Edge version 2 


architectures:
  - build-on: armhf
    run-on: armhf 

grade: devel
confinement: strict

apps:
  iotedge:
    command: usr/bin/iotedge
    environment:
      IOTEDGE_HOST: unix://$SNAP_COMMON/run/mgmt.sock
    plugs:
      - network
      - network-bind
  iotedged:
    command: usr/bin/iotedged -c $SNAP_DATA/etc/iotedge/config.yaml
    daemon: simple
    passthrough:
      after: [dockerd]
    plugs:
      - network
      - network-bind
    sockets:
      workload:
        listen-stream: $SNAP_COMMON/run/workload.sock
        socket-mode: 0666
      mgmt:
        listen-stream: $SNAP_COMMON/run/mgmt.sock
        socket-mode: 0660

parts:
  iotedge:
    plugin: dump
    source: 
      - on armhf: https://github.com/Azure/azure-iotedge/releases/download/1.0.7/iotedge_1.0.7-1_armhf.deb
      # - on armhf: https://github.com/Azure/azure-iotedge/releases/download/1.0.6.1/iotedge_1.0.6.1-1_armhf.deb      
    stage-packages:
      - libgcc1
    override-build: |
      snapcraftctl build
      # also make a lib{ssl,crypto}.so.1.0.2 symlink, as the iotedged binary has this
      # in its lib requirements
      # but the ubuntu archive packages only ship lib{ssl,crypto}.so.1.0.0
      cd $SNAPCRAFT_PART_INSTALL
      # TODO: use the proper "target arch" env var this so could reasonably 
      # still be cross-compiled
      case $(arch) in
        x86_64)
            MULTI_ARCH_PATH="x86_64-linux-gnu";;
        arm*)
            MULTI_ARCH_PATH="arm-linux-gnueabihf";;
        aarch64)
            MULTI_ARCH_PATH="aarch64-linux-gnu";;
        *)
            echo "architecture $ARCH not supported"
            exit 1
            ;;
      esac
      mkdir -p lib/$MULTI_ARCH_PATH
      cd lib/$MULTI_ARCH_PATH
      ln -s libcrypto.so.1.0.0 libcrypto.so.1.0.2
      ln -s libssl.so.1.0.0 libssl.so.1.0.2

  libiothsm:
    plugin: dump
    source: 
      - on armhf: https://github.com/Azure/azure-iotedge/releases/download/1.0.7/libiothsm-std_1.0.7-1_armhf.deb      
  wrapper-scripts:
    plugin: dump
    source: local-assets
    stage-packages:
      - mount
    stage:
      - config/daemon.json
    prime:
      - config/daemon.json